# Generated by Django 5.2.7 on 2025-10-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disaster_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('disaster_type', models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Hurricane', 'Hurricane'), ('Wildfire', 'Wildfire'), ('Pandemic', 'Pandemic'), ('Landslide', 'Landslide'), ('Fire', 'Fire'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('relief_operations', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='disaster_event_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disaster_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='natural_disasters.disaster_event')),
            ],
        ),
    ]
