# Generated by Django 5.2.7 on 2025-10-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natural_disasters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='disaster_event',
            new_name='DisasterEvent',
        ),
        migrations.RenameModel(
            old_name='disaster_event_photo',
            new_name='DisasterEventPhoto',
        ),
    ]
