# Generated by Django 5.2.7 on 2025-11-16 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natural_disasters', '0002_rename_disaster_event_disasterevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disastereventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_photos', to='natural_disasters.disasterevent'),
        ),
    ]
