"""
Django settings for saytaman project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7k6e!r52b)5jmxa$egf1(!nzuxe^2ou***8z-w)j^8=y$b4+$*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.1.2',
    '192.168.1.3',
    '192.168.1.4',
    '192.168.1.5',
    '192.168.1.6',
    '192.168.1.7',
    '192.168.1.8',
    '192.168.1.9',
    '192.168.1.10',
    '192.168.1.11',
    '192.168.1.12',
    '192.168.1.13',
    '192.168.1.14',
    '192.168.1.15',
    '192.168.110.26',
    '10.177.143.82',
    '192.168.100.137',
    ]


# Application definition

INSTALLED_APPS = [
    'members.apps.MembersConfig',
    'vehicles',
    'web_portal',
    'mission_records',
    'natural_disasters',
    'donations_and_expenses',
    'import_export',
    'django_social_share',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # middleware that forces password change after first login
    'members.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'saytaman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saytaman.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'stm',
        'USER': 'HtetMyat582',
        'PASSWORD': '*HMM582zb#',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('my', 'Burmese'),
    ]

TIME_ZONE = 'Asia/Yangon'

USE_I18N = True

USE_TZ = False

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'

DATE_INPUT_FORMATS = [
    '%d-%m-%Y',
    '%Y-%m-%d',
    '%m/%d/%Y',
]

DATE_FORMAT = 'd-m-Y'

# Email settings (development)
# For development use the console backend so reset emails are printed to the console.
# In production configure a real SMTP backend and set a proper DEFAULT_FROM_EMAIL.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@localhost'

# Security: limit the lifetime of password reset tokens (seconds). Default is 3 days (259200).
# Setting to 1 hour (3600) here for better security. Adjust as appropriate for your users.
PASSWORD_RESET_TIMEOUT = 3600


# Define your Page ID and Access Token (For security, load from environment variables 
# or Django settings, NOT hardcoded like this in production!)
PAGE_ID = '100363125746904'
PAGE_ACCESS_TOKEN = 'EAALnhQ8l3hABP396W24upUlDDZBPuJldfkOZAKkg91QZA0ZAvlK01aXK51o5cxn3pTGO1qAkDD8soUabVK26guEr6mF4jivhIUamtSYZAqI5b9mwLYq9kXMKiCGjQmZBZC7VI7iqgzfSs9iJSmbZBnDUhqdNUmQGrqC3WY8bDiX9hmoNgrbHsZAlRbzfqRqWhdSfzjPAUv7T4dX392kKSKBZAjzidYVDF3XjytgVDbrWvcFGZB9SZC3oLwoqJwZDZD'
