# Generated by Django 5.2.7 on 2025-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=20, null=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('donation_type', models.CharField(blank=True, choices=[('ZK', 'Zakat'), ('LL', 'Lillah'), ('BI', 'Bank Interest'), ('Other', 'Other')], max_length=10, null=True)),
                ('donation_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer'), ('KBZ Pay', 'KBZ Pay'), ('Wave Pay', 'Wave Pay'), ('AYA Pay', 'AYA Pay'), ('Other', 'Other')], max_length=20, null=True)),
            ],
        ),
    ]
