# Generated by Django 5.2.7 on 2025-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Service', 'Service')], default='Active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
            ],
        ),
    ]
