# Generated by Django 5.2.7 on 2025-10-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mission_status',
            field=models.CharField(choices=[('On Mission', 'On Mission'), ('Stand-by', 'Stand-by')], default='Stand-by', max_length=20),
        ),
    ]
