# Generated by Django 5.2.7 on 2025-10-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mission_status',
            field=models.CharField(choices=[('On Mission', 'On Mission'), ('Stand-by', 'Stand-by'), ('Unavailable', 'Unavailable')], default='Stand-by', max_length=20),
        ),
    ]
