# Generated by Django 5.2.7 on 2025-10-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_mission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_album', models.ImageField(blank=True, null=True, upload_to='test_photos')),
            ],
        ),
    ]
