# Generated by Django 5.2.7 on 2025-10-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiclephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehiclePhoto',
        ),
    ]
