# Generated by Django 5.2.7 on 2025-11-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_delete_vehiclephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
