# Generated by Django 5.2.7 on 2025-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Patron', 'Patron'), ('Chairman', 'Chairman'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Treasurer', 'Treasurer'), ('Auditor', 'Auditor'), ('Committee Member', 'Committee Member'), ('Member', 'Member'), ('Volunteer', 'Volunteer')], max_length=100)),
                ('nrc', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dob', models.DateField()),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('A+', 'A+'), ('A-', 'A-'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('AB', 'AB'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O', 'O'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('address', models.CharField(blank=True, choices=[('Aungmyaytharzan', 'Aungmyaytharzan'), ('Chanayetharsan', 'Chanayetharsan'), ('Mahaaungmyay', 'Mahaaungmyay'), ('Pyigyitagon', 'Pyigyitagon'), ('Chanmyathazi', 'Chanmyathazi'), ('Patheingyi', 'Patheingyi')], max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_date', models.DateField()),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('husband_or_wife', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
