# Generated by Django 5.0.6 on 2025-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('A+', 'A+'), ('A-', 'A-'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('AB', 'AB'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O', 'O'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
