# Generated by Django 5.0.6 on 2025-10-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, choices=[('Aungmyaytharzan', 'Aungmyaytharzan'), ('Chanayetharsan', 'Chanayetharsan'), ('Mahaaungmyay', 'Mahaaungmyay'), ('Pyigyitagon', 'Pyigyitagon'), ('Chanmyathazi', 'Chanmyathazi'), ('Patheingyi', 'Patheingyi')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
