# Generated by Django 5.0.6 on 2025-10-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_address_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
