# Generated by Django 5.2.7 on 2025-11-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_must_change_password_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Patron', 'Patron'), ('Chairman', 'Chairman'), ('Vice Chairman', 'Vice Chairman'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Treasurer', 'Treasurer'), ('Auditor', 'Auditor'), ('Executive Member', 'Executive Member'), ('Member', 'Member'), ('Volunteer', 'Volunteer')], max_length=100),
        ),
    ]
