# Generated by Django 5.2.7 on 2025-11-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_registration_date_alter_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nrc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
