# Generated by Django 5.2.7 on 2025-10-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mission_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mission_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('donation_received', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('mission_expenses', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assistant_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_1', to='members.member')),
                ('assistant_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_2', to='members.member')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='members.member')),
            ],
        ),
    ]
