# Generated by Django 5.2.7 on 2025-10-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('mission_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mission_record',
            new_name='MissionRecord',
        ),
    ]
