# Generated by Django 5.2.7 on 2025-11-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0002_rename_mission_record_missionrecord'),
        ('vehicles', '0005_delete_vehiclephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicles.vehicle'),
        ),
    ]
