# Generated by Django 5.2.7 on 2025-11-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0003_missionrecord_vehicle'),
        ('vehicles', '0005_delete_vehiclephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicles.vehicle'),
        ),
    ]
