# Generated by Django 5.2.7 on 2025-11-03 20:27

import mission_records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0004_alter_missionrecord_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='mission_number',
            field=models.CharField(default=mission_records.models.MissionRecord.mission_number_generator, max_length=20),
        ),
    ]
