# Generated by Django 5.2.7 on 2025-11-06 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0006_alter_missionrecord_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(110)]),
        ),
    ]
