# Generated by Django 5.2.7 on 2025-11-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0007_alter_missionrecord_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='donation_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionrecord',
            name='fuel_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionrecord',
            name='mission_expenses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
