# Generated by Django 5.2.7 on 2025-11-16 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0008_alter_missionrecord_donation_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRecordPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mission_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_photos', to='mission_records.missionrecord')),
            ],
        ),
    ]
