# Generated by Django 5.2.7 on 2025-11-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0009_missionrecordphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionrecord',
            name='photo',
        ),
    ]
