# Generated by Django 5.2.7 on 2025-11-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0010_remove_missionrecord_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionrecordphoto',
            name='caption',
        ),
    ]
