# Generated by Django 5.2.7 on 2025-11-17 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0011_remove_missionrecordphoto_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrecord',
            name='back_to_hq',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 16, 37, 6, 171768)),
            preserve_default=False,
        ),
    ]
