# Generated by Django 5.2.7 on 2025-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0012_missionrecord_back_to_hq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='back_to_hq',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
