# Generated by Django 5.2.7 on 2025-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0013_alter_missionrecord_back_to_hq'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrecord',
            name='patient_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
