# Generated by Django 5.2.7 on 2025-11-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_nrc'),
        ('mission_records', '0014_missionrecord_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrecord',
            name='created_by',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='mission_created_by', to='members.member'),
            preserve_default=False,
        ),
    ]
