# Generated by Django 5.2.7 on 2025-11-21 20:59

import mission_records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_records', '0015_missionrecord_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='mission_number',
            field=models.CharField(default=mission_records.models.MissionRecord.mission_number_generator, max_length=20, unique=True),
        ),
    ]
